services:
  bot:
    image: ghcr.io/griimmv/alicetele-sqlite:latest
    user: "1000:1000"
    container_name: alicetele-sqlite
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./alicetele/.env.local
    environment:
      DATABASE_PATH: /app/data/alicewiki.db
    volumes:
      - ./alicetele/data:/app/data
