services:
  bot:
    build: .
    image: ghcr.io/griimmv/alicetele-sqlite/alicetele-sqlite:latest
    container_name: alicetele-sqlite
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
